
# Fortishield - Filebeat configuration file
filebeat.modules:
  - module: fortishield
    alerts:
      enabled: true
    archives:
      enabled: false

setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/fortishield-template.json'
setup.template.json.name: 'fortishield'
setup.template.overwrite: true
setup.ilm.enabled: false
output.elasticsearch:
  hosts: ['https://es01:9200']
  username: 'elastic'
  password: 'SecretPassword'
  ssl.verification_mode: full
  ssl.certificate_authorities: ['/etc/ssl/elastic/ca/ca.crt']
  ssl.certificate: '/etc/ssl/elastic/fortishield.manager/fortishield.manager.crt'
  ssl.key: '/etc/ssl/elastic/fortishield.manager/fortishield.manager.key'
